### ISSUE TITLE
Make it an instance method

### ISSUE THREAD

**Issue by domenic** [tc39/proposal-is-usv-string#10]
> Making it a static method on String seems like the safest home for such a method. Adding custom methods to String.prototype is likely quite risky, but could be considered as well.

I don't see much risk here, unlike with Array.prototype. Especially since there's no userland precedent that could cause MooTools-type problems.

An instance method to let you know something about the instance seems best.

**Comment by guybedford** [comment]
If there's no objections to it we could certainly go that route.

**Comment by michaelficarra** [comment]
Done. https://github.com/tc39/proposal-is-usv-string/pull/18
